### ISSUE TITLE
Error using `testOnStartup=11/1221/833`

### ISSUE THREAD

**Issue by zstadler** [nyurik/tilelive-pgquery#1]
It looks like `x` and `y` values are extracted as `NaN` from either `testOnStartup=11/1221/833` or `testOnStartup=11,1221,833`

> ```Verifying pgquery data source by retrieving a tile at [11,NaN,NaN] from postgres:5432...`

When using `"pgquery://?database=$PGDATABASE&$PGHOSTS_LIST&username=$PGUSER&password=$PGPASSWORD&testOnStartup=11/1221/833&funcZXY=gettile&name=OpenMapTiles&errorsAsEmpty=1&maxpool=$MAXCONNECTIONS&key=&nogzip=1"` as the source, the error is:

```
PostgreSQL connection was configured from 
tilelive-pgquery v0.7.0
Server information for postgres:5432:
                 version() = PostgreSQL 9.6.17 on x86_64-pc-linux-gnu (Debian 9.6.17-2.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
    postgis_full_version() = POSTGIS="2.4.8 r17696" PGSQL="96" GEOS="3.6.4-CAPI-1.10.4 ba90ca5" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" LIBPROTOBUF="1.2.1" RASTER
                       jit = unrecognized configuration parameter "jit"
            shared_buffers = 128MB
                  work_mem = 4MB
      maintenance_work_mem = 64MB
      effective_cache_size = 4GB
  effective_io_concurrency = 1
           max_connections = 100
      max_worker_processes = 8
      max_parallel_workers = unrecognized configuration parameter "max_parallel_workers"
  max_parallel_workers_per_gather = 0
               wal_buffers = 4MB
              min_wal_size = 80MB
              max_wal_size = 1GB
          random_page_cost = 4
  default_statistics_target = 100
  checkpoint_completion_target = 0.5

Verifying pgquery data source by retrieving a tile at [11,NaN,NaN] from postgres:5432...
Failed to get a tile at [11,NaN,NaN] from postgres:5432 (in 5ms), aborting tilelive-pgquery initialization:
error: invalid input syntax for integer: "NaN"
/usr/lib/node_modules/@mapbox/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

error: invalid input syntax for integer: "NaN"
    at Connection.parseE (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/lib/node_modules/tilelive-pgquery/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'error',
  length: 92,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '62',
  routine: 'pg_atoi'
}
```

**Comment by zstadler** [comment]
@nyurik 
Given https://github.com/openmaptiles/openmaptiles-tools/pull/317, are there any updates on this?

**Comment by nyurik** [comment]
@zstadler @lazaa32 thx, sorry didn't see it earlier, fixed
